python3 wombo_create.py -p "style test 32" -s 32 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 55" -s 55 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 53" -s 53 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 54" -s 54 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 50" -s 50 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 49" -s 49 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 48" -s 48 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 45" -s 45 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 47" -s 47 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 40" -s 40 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 37" -s 37 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 35" -s 35 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 41" -s 41 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 3" -s 3 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 22" -s 22 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 28" -s 28 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 39" -s 39 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 36" -s 36 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 17" -s 17 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 34" -s 34 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 31" -s 31 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 29" -s 29 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 18" -s 18 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 16" -s 16 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 14" -s 14 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 11" -s 11 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 10" -s 10 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 9" -s 9 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 8" -s 8 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 7" -s 7 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 6" -s 6 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 5" -s 5 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 4" -s 4 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 12" -s 12 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 21" -s 21 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 1" -s 1 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r
python3 wombo_create.py -p "style test 2" -s 2 && python3 wombo_create.py -i && python3 wombo_create.py -d && python3 wombo_create.py -c -r